### ISSUE TITLE
Lists don't seem to work in web app

### ISSUE THREAD

**Issue by kbublitz** [atn832/cel-dart#2]
Hi,

I was trying to use cel in a flutter web application. It looks like the parser has an issue with lists. 

The code runs fine when running the tests, but when I run the same code in the context of my web app, I get parser errors on the debug console and the list is parsed as an empty list. I looked into the generated ast in the debugger and the other parts of the expression look reasonable, just the list doesn't have any elements.

```
        final environment = Environment.standard();
        final ast = environment.compile("value in ['london', 'paris']");
```

Debugging console output:
```
line 1:10 extraneous input ''london'' expecting {']', ','}
line 1:20 extraneous input ''paris'' expecting ']'
```
I also tried simpler expressions, e.g. "[1]" and still get an error message and the result is an empty list.

I am not 100% sure that the issue is related to the web target, but it's the only difference between the test and application execution I can think of right now.

**Comment by atn832** [comment]
I just published the fix to https://pub.dev/packages/cel/changelog#053.

**Comment by kbublitz** [comment]
Wow, that was fast. Thanks for fixing @atn832 
I just updated to the new version and it works perfectly.
